#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jan 12 16:29:52 CET 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim system_wrapper_behav -key {Behavioral:sim_1:Functional:system_wrapper} -tclbatch system_wrapper.tcl -protoinst "protoinst_files/system.protoinst" -log simulate.log"
xsim system_wrapper_behav -key {Behavioral:sim_1:Functional:system_wrapper} -tclbatch system_wrapper.tcl -protoinst "protoinst_files/system.protoinst" -log simulate.log

